import json

with open("In-Context Learning and Prompt Templates-v3-GenAIcourse.ipynb", "r", encoding="utf-8") as f:
    nb = json.load(f)

for cell in nb.get("cells", []):
    if cell.get("cell_type") == "code":
        source = "".join(cell.get("source", []))
        if "ibm-watsonx-ai" in source:
            source = source.replace("!pip install \"ibm-watsonx-ai==1.0.8\" --user\n", "")
            source = source.replace("!pip install \"langchain-ibm==0.1.7\" --user\n", "!pip install \"langchain-community\" --user\n")
            cell["source"] = [s + "\n" if not s.endswith("\n") else s for s in source.split("\n")][:-1]
        elif "ibm_watsonx_ai" in source and "WatsonxLLM" in source:
            new_source = """# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

from langchain_community.llms import Ollama
from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableSequence
from langchain_core.messages import HumanMessage, SystemMessage
from langchain.chains import LLMChain  # Still using this for backward compatibility
"""
            cell["source"] = [line + "\n" for line in new_source.split("\n")[:-1]]
        elif "def llm_model" in source and "WatsonxLLM" in source:
            new_source = """def llm_model(prompt_txt, params=None):
    
    default_params = {
        "temperature": 0.5,
        "top_p": 0.2,
        "top_k": 1
    }

    if params:
        default_params.update(params)
        
    # Remove unsupported keys for Ollama if any, like max_new_tokens
    for key in ["max_new_tokens", "min_new_tokens"]:
        default_params.pop(key, None)

    # Initialize Ollama model
    ollama_llm = Ollama(model="llama3.1", **default_params)
    
    response = ollama_llm.invoke(prompt_txt)
    return response
"""
            cell["source"] = [line + "\n" for line in new_source.split("\n")[:-1]]
        elif "WatsonxLLM" in source and "ibm/granite" in source:
            new_source = """parameters = {
    "temperature": 0.5, # this randomness or creativity of the model's responses
}

llm = Ollama(model="llama3.1", **parameters)
llm
"""
            cell["source"] = [line + "\n" for line in new_source.split("\n")[:-1]]
    elif cell.get("cell_type") == "markdown":
        source = "".join(cell.get("source", []))
        if "watsonx.ai" in source or "WatsonxLLM" in source:
            source = source.replace("IBM's watsonx.ai", "local Ollama")
            source = source.replace("IBM watsonx.ai", "local Ollama")
            source = source.replace("ibm-watsonx-ai", "Ollama")
            source = source.replace("langchain-ibm", "langchain-community")
            source = source.replace("Watsonx.ai", "Ollama")
            source = source.replace("WatsonxLLM", "Ollama")
            source = source.replace("ibm/granite-4-h-small", "llama3.1")
            source = source.replace("Granite", "Llama 3.1")
            cell["source"] = [s + "\n" if not s.endswith("\n") else s for s in source.split("\n")][:-1]

with open("In-Context Learning and Prompt Templates-v3-GenAIcourse.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)
